modLoader="javafml"
loaderVersion="${fml_version_range}"
issueTrackerURL="https://gitlab.com/CDAGaming/UniLib/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/CDAGaming/VersionLibrary/master/UniLib/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/unilib"
logoFile="logo.png"
credits=""
authors="CDAGaming"
description='''
A common set of Utilities, designed for over 50 versions of Minecraft!
'''

[[dependencies.${mod_id}]]
modId="${forge_id}"
mandatory=true
versionRange="${loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${game_version_range}"
ordering="NONE"
side="BOTH"