name: Deploy Maven

on: workflow_dispatch

env:
  CF_APIKEY: ${{ secrets.CF_APIKEY }}
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  NIGHTBLOOM_TOKEN: ${{ secrets.NIGHTBLOOM_TOKEN }}
  MAVEN_USER: ${{ secrets.MAVEN_USER }}
  MAVEN_PASS: ${{ secrets.MAVEN_PASS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: update cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/unimined
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Gradle JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --build-cache --info --stacktrace build

      - name: Deploy to Maven
        run: ./gradlew --build-cache --info --stacktrace publish

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            **/build/libs/
            !build/libs/
            !**/*-dev.jar
            !**/*-shadow.jar
            !**/*-transformProduction*.jar
            !**/testmod*/

      - name: stop daemon
        run: ./gradlew --stop